---
title: "Codon_bias analyses"
output: html_document
editor_options: 
  chunk_output_type: console
---
#initi environment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# setwd("~/Desktop/codon_usage/")
setwd("./")

library('ggplot2')
library('gridExtra')
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(grid)
require(gtable)
library('scales')
library(plyr)
library(reshape2)
```

# Import data
```{r}
relax=read.table('./RELAX_results.txt',header=T,sep='\t')
relax<-melt(relax,id.vars=c('gene','ncodons'))
colnames(relax)[3]='comp'
colnames(relax)[4]='k'
relax$comp<-substr(relax$comp,1,nchar(as.character(relax$comp))-2)
head(relax)


df=read.csv('./CDC.txt',sep='\t',row.names = 1,header=T)
df$Genome
df$Group<-ifelse(df$Genome %in% c('Bathy','SUP05'),'FL',
                 ifelse(df$Genome %in% c('V.okutanii','V.soyoae2','V.diagonalis','V.extenta','V.gigas2'),'Gigas','Ruthia'))
# factor(df$Group)
df %>% head()

```
# Plots

## Distribution of selection intensity parameter K from RELAX analysis
only the K parameter values with a p-value <0.05 are present in the table
```{k}

df$comp<-factor(df$comp, levels=rev(c("SymvsFL", "RuvsFL","GivsFL","GivsRu","SymbAll")))

Kdistrib<-ggplot(subset(df,comp %in% c('SymvsFL','RuvsFL','GivsFL','GivsRu')))+
  theme_bw()+
  # geom_boxplot(aes(x=comp,y=k))+
  geom_violin(aes(x=comp,y=k),fill='grey90')+
  geom_jitter(aes(x=comp,y=k+0.001),width = 0.05,size=0.05)+
  scale_x_discrete(position='top',labels=c('SymvsFL'="Symbionts vs\nfree-living","RuvsFL"='Ruthia vs\nfree-living',"GivsFL"='Gigas vs\nfree-living',"GivsRu"='Gigas vs\nRuthia'))+
  geom_hline(yintercept = 1,color='red')+
  scale_y_log10(limits=c(0.001,50),breaks=c(0.1,seq(0,0.6,0.2),1,seq(5,10,5),seq(25,50,25)))+
  ylab('Selection coefficient (k)')+
  coord_flip()+
  theme(axis.title.y = element_blank(),
        axis.title.x = element_text(size=8),
        plot.margin=unit(c(0.90,0,0,0.25), "cm"))
Kdistrib
```

## Distribution of GC%
```{r distribution GC content}

# qplot(as.numeric(GC),data=df,geom='density',fill=Genome,alpha=0.05)+facet_grid(Genome~.)
# qplot(as.numeric(GC1),data=df,geom='density',fill=Genome,alpha=0.05)+facet_grid(Genome~.)
# qplot(as.numeric(GC2),data=df,geom='density',fill=Genome,alpha=0.05)+facet_grid(Genome~.)
# qplot(as.numeric(GC3),data=df,geom='density',fill=Genome,alpha=0.05)+facet_grid(Genome~.)

colors=list(Gi='#606E96',Ru='#68C47F',FL='#F6EFA1')
levels(df$Group) <- c("Free-living", "Gigas", "Ruthia")
group_names <- c(`FL` = "Free-living",
                    `Gigas` = "Gigas clade",
                    `Ruthia` = "Ruthia clade")
colors_fill=c(Bathy = "#ffa800", SUP05 = "#ff006d", R.magnifica = "#287C8EFF", 
R.phaseoliformis = "#21908CFF", R.pacifica = "#20A486FF", R.rectimargo = "#35B779FF", 
R.pliocardia = "#5DC863FF", R.southwardae = "#8FD744FF", V.okutanii = "#440154FF", 
V.soyoae2 = "#481F70FF", V.diagonalis = "#443A83FF", V.extenta = "#3B528BFF", 
V.gigas2 = "#31688EFF")

df$Group<-factor(df$Group,levels = c('FL','Ruthia','Gigas'))

qplot(as.numeric(GC3),data=df,geom='density',fill=Genome,alpha=0.05)+facet_grid(Group~.)+scale_fill_manual(values=colors_fill)



ggplot(data=subset(df))+geom_hex(aes(x=GC3,y=GC1,fill=..count..),bins=30)+facet_wrap(~Genome)+xlim(c(0,0.6))+ylim(c(0,0.6))

```

## Distribution of CDCs

```{r}
colors_fill=c(Bathy = "#ffa800", SUP05 = "#ff006d", R.magnifica = "#287C8EFF", 
R.phaseoliformis = "#21908CFF", R.pacifica = "#20A486FF", R.rectimargo = "#35B779FF", 
R.pliocardia = "#5DC863FF", R.southwardae = "#8FD744FF", V.okutanii = "#440154FF", 
V.soyoae2 = "#481F70FF", V.diagonalis = "#443A83FF", V.extenta = "#3B528BFF", 
V.gigas2 = "#31688EFF")


# levels(df$Group) <- c("FL", "Gigas", "Ruthia")
df$Group<-factor(df$Group,levels = c('FL','Ruthia','Gigas'))

group_names <- c(`FL` = "Free-living",
                    `Gigas` = "Gigas clade",
                    `Ruthia` = "Ruthia clade")

CDC_spectra<-ggplot(data=subset(df,P.CDC.<0.05))+
  theme_bw()+
  geom_density(aes(x=CDC,color=Group,fill=Genome,y=..density..),color='black',alpha=0.3)+
  scale_x_continuous(limits=c(0,0.35),minor_breaks = seq(0.05, 0.25, by=0.01),breaks=c(0,0.05,0.1,0.15,0.2,0.25,0.3))+
  facet_grid(Group~.,labeller = as_labeller(group_names),switch = 'y')+
  scale_color_manual(values=c(colors$FL,colors$Ru,colors$Gi))+
  scale_fill_manual(values=colors_fill)+
  labs(x='Codon Deviation Coefficient (CDC)',y='Density')+
  theme(strip.background = element_rect(fill = 'white'),
    axis.title.x = element_text(),
    panel.grid.minor.y = element_blank(),
    strip.text.y = element_text(angle=-90)
    )

```

## Biplot: CDC in Symbiont as function of CSC in free-living

```{r}
df %>% head()
bipl<-dcast(df, gene_id ~ Group, value.var = 'CDC', fun=mean,subset=.(P.CDC. < 0.05 ))
head(bipl)



Bi_plot<-ggplot(bipl)+
  theme_bw()+
  geom_point(aes(x=FL,y=Gigas,color='2'),alpha=0.6,size=0.5)+
  geom_point(aes(x=FL,y=Ruthia,color='1',alpha=1-abs(1-(Ruthia/FL))),size=0.5)+
  geom_abline(slope=1,intercept = 0)+
  geom_smooth(aes(x=FL,y=Ruthia,color='1'),fill='grey90',method='lm',se=T,size=0.5)+
  geom_smooth(aes(x=FL,y=Gigas,color='2'),fill='grey90',method='lm',se=T,size=0.5)+
  scale_alpha_continuous(range = c(0.4, 0.6))+
  scale_y_continuous(limits=c(0.05,0.4))+
  scale_x_continuous(limits=c(0.05,0.36))+ expand_limits(x = 0)+
  xlab(label = 'CDC in Free-Living')+ylab(label= 'CDC in symbionts')+
  scale_color_manual(values=c(colors$Ru,colors$Gi),labels=c('Ruthia clade','Gigas clade'),name='')+
  theme(
    legend.text=element_text(size=8))
Bi_plot

#### Arrange plots ###
p3<-grid.arrange(CDC_spectra + theme(legend.position="none"), Bi_plot+ theme(legend.position="none"), nrow=1, widths = unit(c(10,9), "cm"), heights = unit(rep(10, 1), "cm"))
p3

# ggsave(file="Fig3.svg", plot=p3,width = 20,units = 'cm')


```

## Heatmaps

```{r}
#### heatmap ####
library("Hmisc")
library("Cairo")

bipl2<-dcast(df, gene_id ~ Genome, value.var = 'CDC', fun=mean,subset=.(P.CDC. < 0.05))


res2 <- rcorr(as.matrix(bipl2[,c(-1)]),type='pearson')

res<-as.data.frame((res2$r)^2)
hm<-heatmap((res2$r^2),symm = TRUE,sideColors=c("darkgreen", "yellowgreen"), col=terrain.colors(12),legend=col)
hm

# svg(hm,filename='heatmap_pearsons_rsq_corr_cdc.svg',width=40, height=40)

library(gplots)
hm<-heatmap.2(as.matrix(res2$r^2), margins=c(5,8),col=(heat.colors(12)),
        key.xlab="r^2",
        key=TRUE, symkey=FALSE, density.info="none", trace="none")

hm

# pdf(hm,file='heatmap_pearsons_rsq_corr_cdc.pdf',width=40, height=40)
```


# Test correlation of CDC for genome pairs

```{r}
#### For species pair ####
combi=combn(c(2:14), 2)
library("ggpubr")

for(i in c(1:2)){
  shap<-shapiro.test(bipl2[,combi[,i][1]])
  ggqqplot(bipl2[,combi[,i][1]])
  print(shap$p.value)
}

## pearson
for(i in c(1:78)){
cortest<-cor.test(bipl2[,combi[,i][1]],bipl2[,combi[,i][2]], method='pearson',use = "complete.obs")
if(cortest$p.value>0.01){print(colnames(bipl2)[c(combi[,i][1],combi[,i][2])])
  print(cortest$p.value)}}

## kendall
for(i in c(1:78)){
cortest<-cor.test(bipl2[,combi[,i][1]],bipl2[,combi[,i][2]], method='kendall', continuity = T)
if(cortest$p.value>0.01){print(colnames(bipl2)[c(combi[,i][1],combi[,i][2])])
  print(cortest$p.value)}}

## spearman
for(i in c(1:78)){
cortest<-cor.test(bipl2[,combi[,i][1]],bipl2[,combi[,i][2]], method='spearman', continuity = T)
if(cortest$p.value>0.01){print(colnames(bipl2)[c(combi[,i][1],combi[,i][2])])
  print(cortest$p.value)}}


#### For lineage pair ####
bipl
combi=combn(c(2:4), 2)

for(i in c(1:3)){
cortest<-cor.test(bipl[,combi[,i][1]],bipl[,combi[,i][2]], method='pearson')
if(cortest$p.value>0.0001){print(colnames(bipl)[c(combi[,i][1],combi[,i][2])])
  print(cortest$p.value)}}

for(i in c(1:3)){
cortest<-cor.test(bipl[,combi[,i][1]],bipl[,combi[,i][2]], method='kendall', continuity=T)
if(cortest$p.value>0.0001){print(colnames(bipl)[c(combi[,i][1],combi[,i][2])])
  print(cortest$p.value)}}

```
